# Generated by Django 4.1.13 on 2024-09-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadMatchUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countered_by', models.CharField(max_length=255)),
                ('win_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Facet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pickrate', models.FloatField()),
                ('winrate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('winrate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LanePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
                ('winrate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counters', models.CharField(max_length=255)),
                ('win_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('idstring', models.CharField(max_length=255)),
                ('pickrate', models.FloatField()),
                ('winrate', models.FloatField()),
                ('bad_match_ups', models.ManyToManyField(to='myapp.badmatchup')),
                ('facets', models.ManyToManyField(to='myapp.facet')),
                ('good_match_ups', models.ManyToManyField(to='myapp.matchup')),
                ('items', models.ManyToManyField(to='myapp.item')),
                ('lane_presence', models.ManyToManyField(to='myapp.lanepresence')),
            ],
        ),
    ]
